import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-app.js";
import { getFirestore, doc, setDoc, onSnapshot } from "https://www.gstatic.com/firebasejs/10.12.4/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyAyYKY8e_4VcS1eFvb2__7mzMN0MBAow6I",authDomain:"porra-grupos-mundial.firebaseapp.com",projectId:"porra-grupos-mundial",storageBucket:"porra-grupos-mundial.firebasestorage.app",messagingSenderId:"609672730819",appId:"1:609672730819:web:bb4ae4f3f1014b462faa76"};
const ADMIN_PASSWORD="admin2026";const app=initializeApp(firebaseConfig);const db=getFirestore(app);const porraRef=doc(db,"porras","mundial2026");let DATA={participants:[],matches:[]};let admin=false;let editingParticipant=null;const $=id=>document.getElementById(id);
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}function norm(v){return String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"")}function normalize(d){d.participants=d.participants||[];d.matches=d.matches||[];d.matches.forEach(m=>{m.result=m.result||"";m.predictions=m.predictions||{};d.participants.forEach(p=>{if(!(p in m.predictions))m.predictions[p]=""})});return d}function playedCount(){return DATA.matches.filter(m=>m.result).length}function scores(){let played=playedCount();return DATA.participants.map(name=>{let points=0,predicted=0;DATA.matches.forEach(m=>{let pick=m.predictions[name]||"";if(pick)predicted++;if(m.result&&pick===m.result)points++});return{name,points,predicted,ratio:`${points}/${played}`}}).sort((a,b)=>b.points-a.points||a.name.localeCompare(b.name))}function ranked(){let prev=null,rank=0;return scores().map((r,i)=>{if(r.points!==prev){rank=i+1;prev=r.points}return{...r,rank}})}function top10WithTies(){let rows=ranked(),tenth=rows[9];return tenth?rows.filter(r=>r.rank<=tenth.rank):rows}async function save(){await setDoc(porraRef,DATA)}
function row(num,main,side,cls=""){return `<div class="row ${cls}"><span class="num">${num}</span><span>${main}</span><span class="pill">${side}</span></div>`}
function renderHome(){$("playedCounter").textContent=`${playedCount()}/${DATA.matches.length}`;$("rankingTop").innerHTML=top10WithTies().map(r=>row(r.rank,`<strong>${esc(r.name)}</strong><br><span class="small">${r.predicted}/${DATA.matches.length} pronósticos</span>`,r.ratio)).join("")||`<p class="small">Aún no hay participantes.</p>`;let last=[];for(let i=DATA.matches.length-1;i>=0&&last.length<3;i--)if(DATA.matches[i].result)last.push(DATA.matches[i]);$("lastResults").innerHTML=last.map(m=>row(m.id,esc(m.name),m.result)).join("")||`<p class="small">Aún no hay resultados.</p>`;let next=[];for(let m of DATA.matches){if(!m.result&&next.length<3)next.push(m)}$("nextMatches").innerHTML=next.map(m=>row(m.id,esc(m.name),"Pendiente","pending")).join("")||`<p class="small">Todos los partidos tienen resultado.</p>`;let leaders=ranked().filter(r=>r.rank===1).map(r=>r.name).join(", ")||"-";let lastFive=DATA.matches.filter(m=>m.result).slice(-5);let best=scores().map(s=>({name:s.name,hits:lastFive.filter(m=>(m.predictions[s.name]||"")===m.result).length,total:lastFive.length})).sort((a,b)=>b.hits-a.hits||a.name.localeCompare(b.name))[0];$("highlights").innerHTML=`<div class="box"><strong>Líder actual</strong><br>${esc(leaders)}</div><div class="box"><strong>Partidos jugados</strong><br>${playedCount()}/${DATA.matches.length}</div><div class="box"><strong>Últimos 5</strong><br>${best?`${esc(best.name)} · ${best.hits}/${best.total}`:"-"}</div>`}
function smallPrediction(m,name,played){let pick=m.predictions[name]||"-";let cls=played?(pick===m.result?"hit":"miss"):"pending";return row(m.id,esc(m.name),pick,cls)}function participantProfile(name){let sc=ranked().find(r=>r.name===name);let played=DATA.matches.filter(m=>m.result);let lastThree=played.slice(-3),nextThree=DATA.matches.filter(m=>!m.result).slice(0,3),lastFive=played.slice(-5),hits=lastFive.filter(m=>(m.predictions[name]||"")===m.result).length;return `<article class="box"><h3>${esc(name)}</h3><p><strong>Posición:</strong> ${sc?sc.rank+".º":"-"}</p><p><strong>Aciertos:</strong> ${sc?sc.ratio:"0/0"}</p><p><strong>Últimos 5:</strong> ${hits}/${lastFive.length}</p><h4>Últimos 3 pronósticos</h4>${lastThree.map(m=>smallPrediction(m,name,true)).join("")||`<p class="small">Aún no hay resultados.</p>`}<h4>Próximos 3 pronósticos</h4>${nextThree.map(m=>smallPrediction(m,name,false)).join("")||`<p class="small">No quedan próximos partidos.</p>`}<details><summary>Ver todos sus pronósticos</summary>${DATA.matches.map(m=>smallPrediction(m,name,Boolean(m.result))).join("")}</details></article>`}
function matchCard(m){return `<article class="match-card"><h3>${m.id}. ${esc(m.name)}</h3><p><strong>Resultado:</strong> ${m.result||"Pendiente"}</p>${DATA.participants.map(name=>{let pick=m.predictions[name]||"-";let cls=m.result?(pick===m.result?"hit":"miss"):"pending";return `<div class="row ${cls}"><span>${esc(name)}</span><span></span><span class="pill">${pick}</span></div>`}).join("")}</article>`}
function renderSearch(){let q=norm($("searchInput").value);if(!q){$("searchResults").innerHTML=`<p class="small">Busca participante, selección o partido.</p>`;return}let html="";DATA.participants.filter(p=>norm(p).includes(q)).forEach(p=>html+=participantProfile(p));DATA.matches.filter(m=>norm(m.name).includes(q)).forEach(m=>html+=matchCard(m));$("searchResults").innerHTML=html||`<p class="small">Sin resultados.</p>`}
function renderCompare(){let a=$("compareA").value,b=$("compareB").value;if(!a||!b||a===b){$("compareResults").innerHTML=`<p class="small">Elige dos participantes distintos.</p>`;return}let same=0,diff=0,aWins=0,bWins=0,draws=0;let detail=DATA.matches.map(m=>{let pa=m.predictions[a]||"-",pb=m.predictions[b]||"-";pa===pb?same++:diff++;let label="Pendiente";if(m.result){let ha=pa===m.result,hb=pb===m.result;if(ha&&!hb){aWins++;label=`${a} gana`}else if(!ha&&hb){bWins++;label=`${b} gana`}else{draws++;label="Empate"}}return `<div class="box"><strong>${m.id}. ${esc(m.name)}</strong><p>${esc(a)}: <strong>${pa}</strong> · ${esc(b)}: <strong>${pb}</strong></p><p class="small">${esc(label)}</p></div>`}).join("");$("compareResults").innerHTML=`<div class="highlights"><div class="box"><strong>Coincidencias</strong><br>${same}</div><div class="box"><strong>Diferencias</strong><br>${diff}</div><div class="box"><strong>Balance</strong><br>${esc(a)} ${aWins} · ${esc(b)} ${bWins} · Empates ${draws}</div></div>${detail}`}
function options(v){return["","1","X","2"].map(x=>`<option value="${x}" ${x===v?"selected":""}>${x||"-"}</option>`).join("")}function renderTable(){let head=`<thead><tr><th>Partido</th><th>Resultado</th>${DATA.participants.map(p=>`<th>${esc(p)}</th>`).join("")}</tr></thead>`;let body=DATA.matches.map(m=>`<tr><td>${m.id}. ${esc(m.name)}</td><td>${admin?`<select onchange="window.setResult(${m.id}, this.value)">${options(m.result)}</select>`:(m.result||"-")}</td>${DATA.participants.map(name=>renderPredictionCell(m,name)).join("")}</tr>`).join("");$("desktopTable").innerHTML=head+`<tbody>${body}</tbody>`;$("mobileCards").innerHTML=DATA.matches.map(m=>matchCard(m)).join("")}function renderPredictionCell(m,name){let pick=m.predictions[name]||"";let cls=m.result?(pick===m.result?"hit":"miss"):"pending";return `<td class="${cls}">${pick||"-"}</td>`}
function renderSelects(){let opts=`<option value="">Selecciona</option>`+DATA.participants.map(p=>`<option value="${esc(p)}">${esc(p)}</option>`).join("");$("compareA").innerHTML=opts;$("compareB").innerHTML=opts;$("adminParticipantSelect").innerHTML=opts}function renderAdmin(){$("adminTools").classList.toggle("hidden",!admin);$("loginBox").classList.toggle("hidden",admin)}function render(){renderHome();renderSearch();renderSelects();renderCompare();renderTable();renderAdmin()}
window.setResult=async(id,value)=>{let m=DATA.matches.find(x=>x.id===id);if(!m)return;m.result=value;await save()}
function buildPredictionEditor(name){editingParticipant=name;$("predictionEditorTitle").textContent=`Pronósticos de ${name}`;$("predictionList").innerHTML=DATA.matches.map(m=>`<div class="row"><span class="num">${m.id}</span><span>${esc(m.name)}</span><select data-match-id="${m.id}">${options(m.predictions[name]||"")}</select></div>`).join("");$("predictionEditor").classList.remove("hidden")}
$("savePredictions").addEventListener("click",async()=>{if(!editingParticipant)return;let selects=Array.from(document.querySelectorAll("#predictionList select"));if(!selects.every(s=>s.value))return alert("Faltan pronósticos. Para guardar, este participante debe tener los 72.");selects.forEach(s=>{let m=DATA.matches.find(x=>x.id===Number(s.dataset.matchId));m.predictions[editingParticipant]=s.value});await save();alert("Pronósticos guardados.")});
$("createParticipant").addEventListener("click",()=>{let name=$("newParticipantName").value.trim();if(!name)return alert("Escribe un nombre.");if(DATA.participants.includes(name))return alert("Ese participante ya existe.");DATA.participants.push(name);DATA.matches.forEach(m=>m.predictions[name]="");$("newParticipantName").value="";buildPredictionEditor(name);render()});
$("loadParticipantPredictions").addEventListener("click",()=>{let name=$("adminParticipantSelect").value;if(!name)return alert("Elige un participante.");buildPredictionEditor(name)});
$("deleteParticipant").addEventListener("click",async()=>{let name=$("adminParticipantSelect").value;if(!name)return alert("Elige un participante.");if(!confirm(`¿Eliminar a ${name}?`))return;DATA.participants=DATA.participants.filter(p=>p!==name);DATA.matches.forEach(m=>delete m.predictions[name]);editingParticipant=null;$("predictionEditor").classList.add("hidden");await save()});
$("adminOpen").addEventListener("click",()=>$("adminPanel").classList.toggle("hidden"));$("adminLogin").addEventListener("click",()=>{if($("adminPassword").value===ADMIN_PASSWORD){admin=true;$("adminPassword").value="";render()}else alert("Contraseña incorrecta.")});$("adminLogout").addEventListener("click",()=>{admin=false;render()});
$("seedDatabase").addEventListener("click",async()=>{if(!confirm("Esto cargará los 72 partidos iniciales. Hazlo solo si la base está vacía. ¿Continuar?"))return;let res=await fetch("./seed-data.json");DATA=await res.json();await save()});
$("searchInput").addEventListener("input",renderSearch);$("compareA").addEventListener("change",renderCompare);$("compareB").addEventListener("change",renderCompare);
document.querySelectorAll("[data-view]").forEach(btn=>btn.addEventListener("click",()=>{let view=btn.dataset.view;document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$(view).classList.add("active");document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===view))}));
onSnapshot(porraRef,snap=>{if(snap.exists()){DATA=normalize(snap.data());render()}});
